all:
	g++ sharedmemory.cpp --std=c++17 -o sharedmemory
	g++ sharedmemory2.cpp --std=c++17 -o sharedmemory2
	g++ sharedmemory3.cpp --std=c++17 -o sharedmemory3
	g++ sharedmemory4.cpp --std=c++17 -o sharedmemory4
	g++ sharedmemory5.cpp --std=c++17 -o sharedmemory5
clean:
	rm -rf sharedmemory
	rm -rf sharedmemory2
	rm -rf sharedmemory3
	rm -rf sharedmemory4
	rm -rf sharedmemory5
